[colors.primary]
background = "#0B0A17"   # bardzo ciemne tło (inspirowane sceną nocną)
foreground = "#D8D8F8"   # jasny, chłodny fioletowo-biały kolor tekstu

[colors.normal]
black   = "#0B0A17"  # tło
red     = "#FF5CA3"  # neonowy róż (światła w oknach)
green   = "#7DFFC4"  # neonowa mięta (cyber-napisy)
yellow  = "#FFFACD"  # ciepła żółć do subtelnych akcentów
blue    = "#6EC9FF"  # chłodny błękit
magenta = "#D06EFF"  # fiolet do akcentów
cyan    = "#7FFFD4"  # pastelowa zieleń (bliska neonowi)
white   = "#C8C8E8"  # jasna szarość o chłodnym zabarwieniu

[colors.bright]
black   = "#1A1A2F"  # jaśniejszy cień tła
red     = "#FF85B3"  # jaśniejszy neonowy róż
green   = "#A4FFD9"  # jaśniejsza mięta
yellow  = "#FFFBD1"  # rozświetlona żółć
blue    = "#9DDCFF"  # jaśniejszy błękit
magenta = "#E0A9FF"  # jaśniejszy fiolet
cyan    = "#A6FFE0"  # jaśniejszy neon
white   = "#F0F0FF"  # prawie biały fiolet
